# Generated by Django 5.2.1 on 2025-06-03 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_animais', models.IntegerField(default=0)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ovino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_brinco', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('peso', models.FloatField()),
                ('idade_dias', models.IntegerField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('consumo_diario', models.FloatField(default=0.0)),
                ('custo_diario_racao', models.FloatField(default=0.0)),
                ('alimentacao_frequencia_livre', models.BooleanField()),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ovinos.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_horario', models.DateTimeField()),
                ('horario_entrada', models.TimeField()),
                ('duracao_refeicao', models.DurationField()),
                ('consumo', models.FloatField(default=0.0)),
                ('variacao_peso', models.FloatField(default=0.0)),
                ('comportamento', models.TextField(default='')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('ovino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ovinos.ovino')),
            ],
        ),
    ]
