# Generated by Django 5.2.1 on 2025-06-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovinos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovino',
            name='alimentacao_frequencia_livre',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='ovino',
            name='consumo_diario',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ovino',
            name='custo_diario_racao',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ovino',
            name='id_brinco',
            field=models.IntegerField(default=56),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ovino',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='consumo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='variacao_peso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
