# Generated by Django 5.2.1 on 2025-06-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovinos', '0002_alter_ovino_alimentacao_frequencia_livre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refeicao',
            name='comportamento',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='dia_horario',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='duracao_refeicao',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='horario_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
