# Generated by Django 5.2.1 on 2025-06-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovinos', '0005_alter_refeicao_horario_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovino',
            name='id_brinco',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
