# Generated by Django 5.2.1 on 2025-06-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovinos', '0006_alter_ovino_id_brinco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovino',
            name='alimentacao_frequencia_livre',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
